/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          navy: '#00677f',
          cyan: '#00cffd',
        },
        desa: {
          surface: '#f5faff',
          'surface-dim': '#b4e0fc',
          'surface-bright': '#f5faff',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#e9f5ff',
          'surface-container': '#ddf1ff',
          'surface-container-high': '#d1ecff',
          'surface-container-highest': '#c4e7ff',
          'on-surface': '#001e2c',
          'on-surface-variant': '#3c494e',
          'inverse-surface': '#00344a',
          'inverse-on-surface': '#e3f3ff',
          outline: '#6c797f',
          'outline-variant': '#bbc9cf',
          'surface-tint': '#00677f',
          'primary': '#00677f',
          'on-primary': '#ffffff',
          'primary-container': '#00cffd',
          'on-primary-container': '#005469',
          'inverse-primary': '#4dd6ff',
          'secondary': '#006689',
          'on-secondary': '#ffffff',
          'secondary-container': '#1bc0fe',
          'on-secondary-container': '#004b66',
          'tertiary': '#3658ba',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#aabcff',
          'on-tertiary-container': '#2045a8',
          'error': '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          'primary-fixed': '#b7eaff',
          'primary-fixed-dim': '#4dd6ff',
          'on-primary-fixed': '#001f28',
          'on-primary-fixed-variant': '#004e60',
          'secondary-fixed': '#c3e8ff',
          'secondary-fixed-dim': '#79d1ff',
          'on-secondary-fixed': '#001e2c',
          'on-secondary-fixed-variant': '#004c68',
          'tertiary-fixed': '#dce1ff',
          'tertiary-fixed-dim': '#b5c4ff',
          'on-tertiary-fixed': '#00164e',
          'on-tertiary-fixed-variant': '#163ea1',
          'background': '#f5faff',
          'on-background': '#001e2c',
          'surface-variant': '#c4e7ff',
        },
      },
      fontFamily: {
        sans: ['Public Sans', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        headline: ['Public Sans', 'sans-serif'],
        display: ['Public Sans', 'sans-serif'],
        body: ['Public Sans', 'sans-serif'],
        label: ['Public Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
